name: Index Directories & Deploy
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Build index
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Generate directory listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: translations

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: '.'

  deploy:
    name: Deploy to GitHub Pages
    needs: pages-directory-listing
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4.0.0